defaults:
  - base
  - _self_

task_id: high_jump

terrain:
  keyframe_pos: 0.2
  keyframe_pos_offset_range: [-0.15, 0.4]
  terrain_dict: {"parkour_flat": 1.0,
                  "parkour_hurdle": 0,
                  "parkour_wall": 0.0,
                  "parkour_step": 0.0,
                  "parkour_gap": 0.0}
  terrain_length: 6
  terrain_width: 6
  terrain_proportions: [1.0, 0.0, 0.0, 0.0, 0.0] # parkour_flat is the only terrain type

dataset:
  folder: ???
  keyframe_times: [0.1, 0.3, 0.5, 0.7, 1, 1.4, 1.7, 2.0, 2.5, 2.8, 3.4, 3.8, 3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 5.9]
  keyframe_pos_index: [10]
  motion_x_offset: 0.
  keyframe_offset_axis: z
  only_single_keyframe: true
  motion_z_offset: 0.00
  special_scale_index: [10, 18]
  joint_mapping: ${base}/resources/dataset/g1_data/track/joint_id.txt
  init_rotation: [0, 0, -1.57]
  
rewards:
  scales:
    sparse_tracking_trunk_height: 25
 
checkpoint_path: null